"""
tools/email_tool.py — SMTP tool for delivering CI digests via email.
"""

from __future__ import annotations

import json
import smtplib
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import structlog
from langchain_core.tools import tool

from config import settings

logger = structlog.get_logger(__name__)

@tool
async def send_email_digest(
    company_name: str,
    category: str,
    signal_level: str,
    report_text: str,
    confidence: float = 0.7,
) -> str:
    """
    Send a competitive intelligence digest to the configured recipient email address.

    Use this alongside or instead of send_slack_digest to deliver reports via email.
    The report will be formatted as an HTML email with clear signal levels.

    signal_level must be one of: "high", "medium", "low"
    """
    if not all([settings.smtp_host, settings.smtp_user, settings.smtp_password, settings.recipient_email]):
        logger.warning("Email (SMTP) not fully configured — skipping email delivery")
        return json.dumps({
            "sent": False,
            "reason": "SMTP settings or recipient_email not configured in .env",
            "company": company_name,
        })

    # Signal level formatting
    signal_colors = {
        "high": "#fee2e2", # red-100
        "medium": "#fef9c3", # yellow-100
        "low": "#dcfce7", # green-100
    }
    signal_text_colors = {
        "high": "#991b1b",
        "medium": "#854d0e",
        "low": "#166534",
    }
    
    color = signal_colors.get(signal_level, "#f3f4f6")
    text_color = signal_text_colors.get(signal_level, "#374151")
    date = datetime.utcnow().strftime("%d %b %Y, %H:%M UTC")

    # Create message
    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"[{signal_level.upper()}] CI Update: {company_name}"
    msg["From"] = settings.smtp_from_email or settings.smtp_user
    msg["To"] = settings.recipient_email

    # HTML Body
    html = f"""
    <html>
    <body style="font-family: sans-serif; color: #1f2937; line-height: 1.5; padding: 20px;">
        <div style="max-width: 600px; margin: 0 auto; border: 1px solid #e5e7eb; borderRadius: 8px; overflow: hidden;">
            <div style="background-color: #1e3a8a; color: white; padding: 20px; text-align: center;">
                <h2 style="margin: 0;">Competitive Intelligence Report</h2>
                <p style="margin: 5px 0 0 0; opacity: 0.8;">{company_name} | {category or 'General'}</p>
            </div>
            
            <div style="padding: 20px;">
                <div style="background-color: {color}; color: {text_color}; padding: 10px 15px; border-radius: 6px; font-weight: bold; display: inline-block; margin-bottom: 20px;">
                    SIGNAL LEVEL: {signal_level.upper()}
                </div>
                
                <div style="margin-bottom: 20px; font-size: 14px; color: #6b7280;">
                    <strong>Confidence:</strong> {confidence:.0%} | <strong>Date:</strong> {date}
                </div>
                
                <div style="border-top: 1px solid #e5e7eb; padding-top: 20px; white-space: pre-wrap;">
                    {report_text}
                </div>
                
                <div style="margin-top: 30px; padding-top: 15px; border-top: 1px solid #e5e7eb; font-size: 12px; color: #9ca3af; text-align: center;">
                    🤖 Generated by Multi-Agent CI Automator<br/>
                    <em>Please verify critical signals before acting.</em>
                </div>
            </div>
        </div>
    </body>
    </html>
    """
    
    msg.attach(MIMEText(report_text, "plain"))
    msg.attach(MIMEText(html, "html"))

    try:
        # Use TLS
        with smtplib.SMTP(settings.smtp_host, settings.smtp_port) as server:
            server.starttls()
            server.login(settings.smtp_user, settings.smtp_password)
            server.send_message(msg)
            
        logger.info("Email digest sent", company=company_name, recipient=settings.recipient_email)
        return json.dumps({
            "sent": True,
            "company": company_name,
            "recipient": settings.recipient_email,
            "signal_level": signal_level
        })
    except Exception as e:
        logger.error("Email send failed", error=str(e))
        return json.dumps({"sent": False, "error": str(e), "company": company_name})
