"""
tools/slack_tool.py — Slack Incoming Webhook tool for delivering CI digests.

WHAT IS A SLACK INCOMING WEBHOOK?
    A Webhook URL that lets any application POST a message to a Slack channel.
    No OAuth, no bot setup — just a URL you POST JSON to.
    Completely free. No API rate limits for webhooks (within reason).

HOW TO SET UP (2 minutes):
    1. Go to https://api.slack.com/apps
    2. Create New App → From Scratch
    3. Add feature: "Incoming Webhooks" → Activate
    4. Click "Add New Webhook to Workspace" → choose channel
    5. Copy the webhook URL → paste into SLACK_WEBHOOK_URL in .env

SLACK BLOCK KIT:
    Instead of plain text, Slack uses "Block Kit" — structured JSON that
    renders beautifully with sections, dividers, and formatted text.
    We use it to create digest messages with:
    - Header with emoji signal level
    - Company name and category
    - Findings sections (news, funding, reviews, hiring)
    - Timestamp footer

FREE ALTERNATIVE (if no Slack):
    Discord webhooks work identically — same JSON format.
    Set DISCORD_WEBHOOK_URL and call the same POST.
"""

from __future__ import annotations

import json
from datetime import datetime

import httpx
import structlog
from langchain_core.tools import tool

from config import settings

logger = structlog.get_logger(__name__)

# Signal level → emoji + color for Slack messages
SIGNAL_EMOJI = {
    "high":   "🔴",
    "medium": "🟡",
    "low":    "🟢",
}
SIGNAL_LABEL = {
    "high":   "HIGH SIGNAL — Action Required",
    "medium": "MEDIUM SIGNAL — Worth Noting",
    "low":    "LOW SIGNAL — Routine Update",
}


def _build_slack_blocks(
    company_name: str,
    category: str,
    signal_level: str,
    report_text: str,
    confidence: float,
) -> list[dict]:
    """
    Build Slack Block Kit blocks for a CI digest message.

    Block Kit is Slack's structured message format — much better than plain text.
    Sections, dividers, and markdown formatting all render natively in Slack.
    """
    emoji  = SIGNAL_EMOJI.get(signal_level, "⚪")
    label  = SIGNAL_LABEL.get(signal_level, "Update")
    date   = datetime.utcnow().strftime("%d %b %Y, %H:%M UTC")

    # Truncate report if too long for Slack (3000 char limit per block)
    display_text = report_text[:2800] + "..." if len(report_text) > 2800 else report_text

    blocks = [
        # Header
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": f"{emoji} Competitive Intel: {company_name}",
                "emoji": True
            }
        },
        # Signal level + category
        {
            "type": "section",
            "fields": [
                {"type": "mrkdwn", "text": f"*Signal Level:*\n{emoji} {label}"},
                {"type": "mrkdwn", "text": f"*Category:*\n{category or 'General'}"},
                {"type": "mrkdwn", "text": f"*Confidence:*\n{confidence:.0%}"},
                {"type": "mrkdwn", "text": f"*Generated:*\n{date}"},
            ]
        },
        {"type": "divider"},
        # Report content
        {
            "type": "section",
            "text": {"type": "mrkdwn", "text": display_text}
        },
        {"type": "divider"},
        # Footer
        {
            "type": "context",
            "elements": [
                {
                    "type": "mrkdwn",
                    "text": "🤖 Generated by Multi-Agent CI Automator | _Verify before acting on HIGH signals_"
                }
            ]
        }
    ]
    return blocks


@tool
async def send_slack_digest(
    company_name: str,
    category: str,
    signal_level: str,
    report_text: str,
    confidence: float = 0.7,
) -> str:
    """
    Send a competitive intelligence digest to the configured Slack channel.

    Use this AFTER completing the research and summary for a company.
    This is the final step in the CI pipeline — delivering the report.

    signal_level must be one of: "high", "medium", "low"
    - high:   major event (funding, acquisition, executive change, major product launch)
    - medium: notable update (new feature, hiring signal, pricing change)
    - low:    routine update (blog post, conference, minor news)

    confidence: float 0.0-1.0 — how confident you are in the findings

    Example:
        send_slack_digest(
            company_name="Freshworks",
            category="CRM",
            signal_level="high",
            report_text="Freshworks raised $150M Series H...",
            confidence=0.92
        )
    """
    webhook_url = settings.slack_webhook_url
    if not webhook_url:
        logger.warning("SLACK_WEBHOOK_URL not configured — skipping Slack delivery")
        return json.dumps({
            "sent": False,
            "reason": "SLACK_WEBHOOK_URL not configured in .env",
            "company": company_name,
        })

    # Validate signal level
    if signal_level not in ("high", "medium", "low"):
        signal_level = "low"

    blocks = _build_slack_blocks(
        company_name=company_name,
        category=category,
        signal_level=signal_level,
        report_text=report_text,
        confidence=confidence,
    )

    payload = {
        "text": f"{SIGNAL_EMOJI.get(signal_level, '⚪')} CI Update: {company_name}",
        "blocks": blocks,
    }

    async with httpx.AsyncClient(timeout=10) as client:
        try:
            resp = await client.post(webhook_url, json=payload)
            resp.raise_for_status()
            logger.info("Slack digest sent", company=company_name, signal=signal_level)
            return json.dumps({
                "sent": True,
                "company": company_name,
                "signal_level": signal_level,
                "channel": "configured Slack channel",
            })
        except httpx.HTTPStatusError as e:
            logger.error("Slack webhook failed", status=e.response.status_code, body=e.response.text)
            return json.dumps({
                "sent": False,
                "error": f"Slack returned HTTP {e.response.status_code}",
                "company": company_name,
            })
        except Exception as e:
            logger.error("Slack send failed", error=str(e))
            return json.dumps({"sent": False, "error": str(e), "company": company_name})
